import { Check, Sparkles } from 'lucide-react'
import { useState } from 'react'
import { Button } from '../../../components/ui/Button'
import { useToast } from '../../../components/ui/Toast'
import type { DailyRecord } from '../../../types'
import { organizeReviewPrompt, reviewPrompt } from '../prompts/prompts'
import { aiDailyInsightSchema, aiReviewDraftSchema, parseAIJson, type AIDailyInsight, type AIReviewDraft } from '../schemas/aiResponses'
import { currentAIContext, generateAI } from '../services/aiService'

export function AIDailyReviewTools({date,value,onApply}:{date:string;value:DailyRecord;onApply:(draft:Partial<DailyRecord>)=>void}){const[insight,setInsight]=useState<AIDailyInsight>();const[draft,setDraft]=useState<AIReviewDraft>();const[working,setWorking]=useState<'analysis'|'organize'|undefined>();const toast=useToast();const analyze=async()=>{setWorking('analysis');try{setInsight(parseAIJson(await generateAI('review',reviewPrompt(currentAIContext(date)),date),aiDailyInsightSchema,'review'))}catch(error){toast(error instanceof Error?error.message:'分析失败。','error')}finally{setWorking(undefined)}};const organize=async()=>{const raw=[value.review,value.achievement,value.problem,value.satisfaction,value.nextStep].filter(Boolean).join('\n');if(!raw)return toast('先写下一些原始复盘内容，AI 才能帮你整理。','error');setWorking('organize');try{setDraft(parseAIJson(await generateAI('organize-review',organizeReviewPrompt(raw,currentAIContext(date)),date),aiReviewDraftSchema,'organize-review'))}catch(error){toast(error instanceof Error?error.message:'整理失败。','error')}finally{setWorking(undefined)}};return <section className="ai-review-tools"><div className="ai-review-tools__actions"><Button variant="secondary" disabled={!!working} onClick={analyze}><Sparkles/>{working==='analysis'?'正在分析今天…':'AI 分析今天'}</Button><Button variant="ghost" disabled={!!working} onClick={organize}>AI 帮我整理</Button></div>{insight&&<article className="ai-insight"><h3>AI 复盘分析</h3><p>{insight.summary}</p><div><b>数据事实</b><ul>{insight.facts.map(item=><li key={item}>{item}</li>)}</ul></div><div><b>AI 推断</b><ul>{insight.inferences.map(item=><li key={item}>{item}</li>)}</ul></div><div><b>明日建议</b><ol>{insight.suggestions.map(item=><li key={item}>{item}</li>)}</ol></div></article>}{draft&&<article className="ai-review-draft"><h3>AI 整理草稿</h3><p>{draft.review}</p><Button onClick={()=>{onApply(draft);setDraft(undefined)}}><Check/>应用到复盘</Button></article>}</section>}
