import { Check, Sparkles, X } from 'lucide-react'
import { useState } from 'react'
import { Button } from '../../../components/ui/Button'
import { useToast } from '../../../components/ui/Toast'
import { createId } from '../../../lib/id'
import { useAppStore } from '../../../stores/appStore'
import type { Priority, Task } from '../../../types'
import { planPrompt } from '../prompts/prompts'
import { aiTaskPlanSchema, parseAIJson, type AITaskPlan } from '../schemas/aiResponses'
import { currentAIContext, generateAI } from '../services/aiService'

export function AIPlannerDrawer({ date,onClose }: { date:string;onClose:()=>void }) { const store=useAppStore();const[input,setInput]=useState('');const[items,setItems]=useState<AITaskPlan>();const[selected,setSelected]=useState<Set<number>>(new Set());const[working,setWorking]=useState(false);const controller=useState(()=>new AbortController())[0];const toast=useToast()
const generate=async()=>{if(!input.trim())return toast('告诉 AI 今天有哪些时间和学习目标。','error');setWorking(true);try{const text=await generateAI('planner',planPrompt(input,currentAIContext(date)),date,undefined,controller.signal);const next=parseAIJson(text,aiTaskPlanSchema);setItems(next);setSelected(new Set(next.map((_,index)=>index)))}catch(error){toast(error instanceof Error?error.message:'生成失败。','error')}finally{setWorking(false)}}
const add=async()=>{if(!items)return;const now=new Date().toISOString();const themeByName=new Map(store.themes.map(item=>[item.name,item.id]));const subjectByName=new Map(store.subjects.map(item=>[item.name,item.id]));const planned=items.filter((_,index)=>selected.has(index));if(!planned.length)return toast('请至少选择一项建议。','error');for(const item of planned){const task:Task={id:createId(),date,themeId:themeByName.get(item.theme??'')??store.themes[0]?.id??'',subjectId:subjectByName.get(item.subject??'')??store.subjects[0]?.id??'',name:item.title,detail:item.subtasks.join('\n'),priority:item.priority as Priority,status:'todo',plannedDuration:item.plannedDuration,actualDuration:0,output:'',note:'',order:Date.now()+Math.random(),createdAt:now,updatedAt:now};await store.saveTask(task)}toast(`已添加 ${planned.length} 项确认后的任务。`);onClose()}
return <div className="ai-drawer-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><aside className="ai-drawer ai-planner" role="dialog" aria-modal="true"><header><div><span className="eyebrow">AI 安排</span><h2>把今天的学习时间排得更现实。</h2><p>AI 只生成任务草稿；勾选并确认后才会添加到今天。</p></div><button className="icon-button" onClick={onClose}><X/></button></header><div className="ai-drawer__body"><label>今天的可用时间与想做的事<textarea value={input} onChange={event=>setInput(event.target.value)} placeholder="例如：今天下午有 3 小时，想复习 C 指针、学习 STM32 串口；数学建模有时间再看。"/></label><div className="ai-inline-actions"><Button disabled={working} onClick={generate}><Sparkles/>{working?'正在安排…':'生成任务草稿'}</Button>{working&&<Button variant="ghost" onClick={()=>controller.abort()}>停止生成</Button>}</div>{items&&<div className="ai-result-list"><p>AI 建议今天安排 {items.length} 项任务。你可以修改后再确认。</p>{items.map((item,index)=><label className="ai-plan-item" key={`${item.title}-${index}`}><input type="checkbox" checked={selected.has(index)} onChange={()=>setSelected(current=>{const next=new Set(current);next.has(index)?next.delete(index):next.add(index);return next})}/><div><span>{item.priority} · {item.plannedDuration} 分钟</span><input value={item.title} onChange={event=>setItems(current=>current?.map((entry,i)=>i===index?{...entry,title:event.target.value}:entry)??current)}/><textarea value={item.subtasks.join('\n')} onChange={event=>setItems(current=>current?.map((entry,i)=>i===index?{...entry,subtasks:event.target.value.split('\n').filter(Boolean)}:entry)??current)}/><small>{item.reason}</small></div></label>)}</div>}</div><footer><span>不会覆盖或移动既有任务。</span><Button disabled={!items||working} onClick={add}><Check/>添加选中的 {selected.size} 项任务</Button></footer></aside></div> }
