import { Check, Sparkles, X } from 'lucide-react'
import { useState } from 'react'
import { Button } from '../../../components/ui/Button'
import { useToast } from '../../../components/ui/Toast'
import { createId } from '../../../lib/id'
import { useAppStore } from '../../../stores/appStore'
import type { Task } from '../../../types'
import { breakdownPrompt } from '../prompts/prompts'
import { aiTaskBreakdownSchema, parseAIJson, type AITaskBreakdown } from '../schemas/aiResponses'
import { currentAIContext, generateAI } from '../services/aiService'

export function AITaskBreakdownDrawer({task,onClose}:{task:Task;onClose:()=>void}){const {saveTask}=useAppStore();const[plan,setPlan]=useState<AITaskBreakdown>();const[working,setWorking]=useState(false);const toast=useToast();const generate=async()=>{setWorking(true);try{setPlan(parseAIJson(await generateAI('breakdown',breakdownPrompt(task,currentAIContext(task.date)),task.date),aiTaskBreakdownSchema))}catch(error){toast(error instanceof Error?error.message:'生成失败。','error')}finally{setWorking(false)}};const applyDetails=async()=>{if(!plan)return;await saveTask({...task,detail:plan.steps.map((step,index)=>`${index+1}. ${step.title}${step.detail?`：${step.detail}`:''}`).join('\n'),updatedAt:new Date().toISOString()});toast('已将确认后的拆解写入子任务。');onClose()};const createTasks=async()=>{if(!plan)return;const now=new Date().toISOString();for(const step of plan.steps)await saveTask({...task,id:createId(),name:step.title,detail:step.detail??'',plannedDuration:step.estimatedMinutes,status:'todo',actualDuration:0,output:'',note:'',order:Date.now()+Math.random(),createdAt:now,updatedAt:now});toast('已创建确认后的独立任务。');onClose()};return <div className="ai-drawer-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><aside className="ai-drawer" role="dialog"><header><div><span className="eyebrow">AI 拆解任务</span><h2>{task.name}</h2><p>先查看草稿，再选择写入子任务或创建独立任务。</p></div><button className="icon-button" onClick={onClose}><X/></button></header><div className="ai-drawer__body">{!plan?<Button disabled={working} onClick={generate}><Sparkles/>{working?'正在拆解…':'生成拆解草稿'}</Button>:<div className="ai-breakdown"><p className={plan.suitableForOneDay?'is-ok':'is-warning'}>{plan.warning??(plan.suitableForOneDay?'该任务适合在一天内推进。':'该任务可能需要分阶段完成。')}</p><ol>{plan.steps.map(step=><li key={step.title}><b>{step.title}</b><span>{step.estimatedMinutes} 分钟</span><small>{step.detail}</small></li>)}</ol></div>}</div>{plan&&<footer><Button variant="secondary" onClick={applyDetails}><Check/>仅写入子任务</Button><Button onClick={createTasks}><Check/>拆成独立任务</Button></footer>}</aside></div>}
