import { z } from 'zod'

const category=z.object({id:z.string(),name:z.string(),color:z.string(),order:z.number(),createdAt:z.string(),updatedAt:z.string()})
const settings=z.object({id:z.literal('app'),startDate:z.string(),endDate:z.string(),goalDays:z.number(),goalStudyHours:z.number(),goalTaskCount:z.number(),dailyGoalMinutes:z.number(),weeklyGoalMinutes:z.number(),autoCheckUpdates:z.boolean().default(true),updateChannel:z.literal('stable').default('stable'),lastUpdateCheckAt:z.string().optional(),lastDesktopBackupAt:z.string().optional(),updatedAt:z.string()})
const task=z.object({id:z.string(),date:z.string(),themeId:z.string(),subjectId:z.string(),templateId:z.string().optional(),name:z.string(),detail:z.string(),priority:z.enum(['P1','P2','P3']),status:z.enum(['todo','doing','done','missed','cancelled']),plannedDuration:z.number(),actualDuration:z.number(),focusScore:z.number().optional(),energyScore:z.number().optional(),output:z.string(),note:z.string(),order:z.number(),createdAt:z.string(),updatedAt:z.string()})
const record=z.object({date:z.string(),checkedIn:z.boolean(),checkinTime:z.string().optional(),isMakeup:z.boolean(),review:z.string(),nextStep:z.string(),achievement:z.string(),problem:z.string(),satisfaction:z.string(),mood:z.number().optional(),createdAt:z.string(),updatedAt:z.string()})
const aiConfig=z.object({id:z.string(),displayName:z.string(),provider:z.enum(['openai-compatible','deepseek','gemini','custom']),baseUrl:z.string(),model:z.string(),enabled:z.boolean(),isDefault:z.boolean(),temperature:z.number().optional(),maxTokens:z.number().optional(),timeout:z.number().optional(),streamEnabled:z.boolean().optional(),createdAt:z.string(),updatedAt:z.string(),apiKey:z.null()})
const aiPreferences=z.object({id:z.literal('preferences'),permissions:z.object({tasks:z.boolean(),durations:z.boolean(),focus:z.boolean(),reviews:z.boolean(),goals:z.boolean(),recentHistory:z.boolean()}),outputLanguage:z.enum(['follow-app','zh-CN','en-US']).default('follow-app'),consentedAt:z.string().optional(),updatedAt:z.string()})
export const backupSchema=z.object({schemaVersion:z.number(),exportedAt:z.string(),settings,themes:z.array(category.extend({icon:z.string()})),subjects:z.array(category),templates:z.array(z.object({id:z.string(),name:z.string(),detail:z.string(),themeId:z.string().optional(),subjectId:z.string().optional(),priority:z.enum(['P1','P2','P3']),plannedDuration:z.number(),order:z.number(),createdAt:z.string(),updatedAt:z.string()})),tasks:z.array(task),dailyRecords:z.array(record),aiConfigs:z.array(aiConfig).optional(),aiPreferences:aiPreferences.optional()})
export const parseBackup=(raw:string)=>backupSchema.parse(JSON.parse(raw))
